### ISSUE TITLE
Add option to export/download the contents shown on the table

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#117]
Some users have raised the concern that they want to copy/paste information from the table but they cannot do it properly. A possible workaround would be to offer a download/export results options which would allow the user to get a CSV or JSON representation of the search/filter results.

**Comment by prustar** [comment]
@acorbi and provide a specific URL link for sharing and referencing that would reflect the organisation owner of the data. i.e. a Cambodian dataset would have 'Cambodia' in the URL to reflect ODC regardless of access through ODM.

**Comment by acorbi** [comment]
@prustar that would not work in all cases. For instance:

- user is browsing the data page on ODM, sets some filters and search terms which return records owned by different organizations (ODC, ODMm). What to add on that link then?

**Comment by prustar** [comment]
@acorbi -- not sure but is an issue for M&E which @tthy raised. We need to find a reasonable solution.

**Comment by acorbi** [comment]
@prustar can you provide more details about that issue @tthy raised? With more insight I might be able to propose some alternative solution.

**Comment by prustar** [comment]
@acorbi -- raising it in SC meeting today.

**Comment by acorbi** [comment]
@prustar let's rather discuss the URL issue on https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/issues/119, this one should only be about the download/export function.

**Comment by prustar** [comment]
@acorbi -- is configuring this difficult to do? It's a pretty basic function that we could offer in terms of features that would add value from what we have currently. This then could be reproduced for all the tablular pages and profiles as well.
