### ISSUE TITLE
Revise terminology used in search terms and filter options in Laws pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#118]
Feedback gathered from users indicate that some wording needs to be changed on the Laws pages

- [x] Taxonomy → suggest using ‘Topics’ instead
- [x] Library records → has been mentioned that this is confusing from various people. Alternative terms: Publications or Resources
- [ ] Promulgation date → We need to simply state ‘date’
- [ ] Source → For library records should be publisher / author

@Huyeng @thetaung2 @ChandaraKhun @prustar @gimmemochi @DBishton please provide some comments if you have any

**Comment by prustar** [comment]
Everyone as these terms are inputted in the back end manually by the editors we need to be consistent and apply across the platform.  I think using Topic and Date are self-explanatory but for source and library what do people prefer?

**Comment by acorbi** [comment]
@Huyeng @ChandaraKhun the **Promulgation date** and **Source** name for fields are specified on the tabular page's configuration. No code change need for this besides adding the strings to translate to transifex.

**Comment by Huyeng** [comment]
@acorbi - using date instead of the Promulgation date, it will be confuse. What is the date refers to, published date, promulgation date or what?

> the Promulgation date and Source name for fields are specified on the tabular page's configuration. No code change need for this besides adding the strings to translate to transifex.

Do you mean the table's title on law page?
I'm pretty sure that the name of Promulgation date or other titles on law's table are translated before ODC conducted the workshop last year.

**Comment by acorbi** [comment]
@Huyeng 

> Do you mean the table's title on law page?

What I mean is that the Names **Date/Promulgation date** and/or **Source** are specified on the configuration of the tabular page as seen below.

Both for the column names:

![screenshot from 2017-01-26 16-19-13](https://cloud.githubusercontent.com/assets/384894/22336675/4e968270-e3e3-11e6-8140-603efab57a28.png)

and for the filters:

![screenshot from 2017-01-26 16-19-55](https://cloud.githubusercontent.com/assets/384894/22336672/4be2582e-e3e3-11e6-893b-6cfef6ae6a76.png)
