### ISSUE TITLE
Errors when filtering Land Concessions Contract in Khmer language

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#152]
Steps to reproduce the error.

1. go to https://opendevelopmentcambodia.net/database/laws-policies-and-agreements
2. On **content types** select **agreements**
3. On **document type** select **land concessions contract**
4. Click Search, now items are filtered and only 3 Land concession contracts appear. So far is good.

![screenshot from 2017-03-01 10-20-47](https://cloud.githubusercontent.com/assets/384894/23453547/0ae3781c-fe69-11e6-9568-58fadee82f7c.png)

5. Switch the language to khmer, then a warning appears, the **document type** filter shows the id and not the label of the value and 0 results are shown:

```warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/wp-odm_tabular_pages/post-types/templates/single-tabular.php on line 120```

![screenshot from 2017-03-01 10-20-22](https://cloud.githubusercontent.com/assets/384894/23453560/18604cf4-fe69-11e6-89da-5d7c0f2c1262.png)

**Comment by Huyeng** [comment]
@acorbi  could you please reproduce if the error has gone?

**Comment by acorbi** [comment]
now is fixed. great @Huyeng ! closing
