### ISSUE TITLE
Warning appearing when selecting Agreements/All in Khmer language

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#153]
Steps to reproduce the issue:

1. Go to https://opendevelopmentcambodia.net/km/database/laws-policies-and-agreements
2. Select content type = Agreement
3. Select document type = All
4. Following warning appears:

```Warning: implode(): Invalid arguments passed in /var/www/html/wp-content/plugins/wp-odm_tabular_pages/post-types/templates/odc-laws-template.php on line 133```

![screenshot from 2017-03-01 10-33-46](https://cloud.githubusercontent.com/assets/384894/23453975/cfe60110-fe6a-11e6-80b1-98e52b74b630.png)

https://opendevelopmentcambodia.net/km/database/laws-policies-and-agreements?query=&taxonomy=all&group_type=agreement&odm_document_type=all

**Comment by Huyeng** [comment]
Missing configuration in Khmer.
