### ISSUE TITLE
The filter select box in law page is overlap the drop down menu

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#162]
Please decrease the z-index of filter select smaller that menu drop down list.
<img width="948" alt="screenshot at apr 24 22-01-55" src="https://cloud.githubusercontent.com/assets/6613530/25343840/69317062-293a-11e7-998a-88d4e42276ef.png">

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/commit/220774d1b93ddd9e5b58cd1b3c8c5009fd283b03
