### ISSUE TITLE
Improve laws filtering functionalities (advanced)

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#21]
Additional filters:

Tabular pages should be adapted in a way which allow the editor to select a series of filter parameters which correspond to data tables. 
- Document type: This should be implemented as a multi-selectable control which has initially all its options selected and would allow the user to disable/hide some of them.
- Issuing agency

Also other filters which are not strickly linked to a data table.
- Document number 
- Date

Following configuration options to offer:
- Specify list of filters:
  filter_name: to build queries
  filter_type: to present suitable controls and options

**Comment by prustar** [comment]
@acorbi see https://docs.google.com/document/d/1SubUAQmYWwFvyPgJLoE4IZauyMfh5l9fLfgQeF611QI/edit

for use cases and additional filters.
