### ISSUE TITLE
Laws, policies and agreements errors with array_keys

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#27]
![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/20376766/2b42d3e0-acbc-11e6-8e64-b26f55c5cef9.jpg)

**Comment by acorbi** [comment]
@Huyeng the tabular pages (laws pages) need to be configured now -> https://wiki.opendevelopmentmekong.net/partners:tabular_pages.

Now it's fixed.

You will notice that the filter by document type is currently mising, I will implement new (configurable) filtering possibilities as part of 2.1.0
