### ISSUE TITLE
The law page in Khmer not showing the Khmer texts, those titles should falback to english

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#31]
All the title in Khmer are hidden, and the some other fields are not showed in Khmer.

https://opendevelopmentcambodia.net/km/tabular/laws-profiles-and-agreements
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/20792041/668f6df0-b7f2-11e6-91e9-ce312f74d16b.jpg)

**Comment by acorbi** [comment]
@Huyeng it is not ALL the titles, just some of them. If you click on the column title, to sort the rows by title, you will see there are titles indeed:

![screenshot from 2016-12-01 12-39-48](https://cloud.githubusercontent.com/assets/384894/20792676/62f35e56-b7c3-11e6-8d2d-fda51bd6ab78.png)

The solution to this problem should be by checking those records and making sure they have titles set in Khmer.

**Comment by Huyeng** [comment]
You are right.  Since our team are quite busy to complete some priority tasks by the end of this year, I would like to suggest to show English title instead of blank. The team is planning to to fill those khmer titles in early next year.

**Comment by acorbi** [comment]
@Huyeng agreed, this Issue should be fixed by implementing a fallback solution so english titles are shown when khmer titles are not present.

Pinging @tthy since he mentioned this Issue on today's SC meeting

**Comment by acorbi** [comment]
This issue is now resolved
