### ISSUE TITLE
Law page: Suggest to remove the Khmer words that are written in English on Document type column

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#32]
The Khmer words that are written in English are reappeared after code updated. Suggest to remove those Khmer sounds, show only the English words. 
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/20873406/b000f3f2-bad9-11e6-87a2-3a49c8b6f607.jpg)

**Comment by acorbi** [comment]
@Huyeng This is not hard-coded anymore. The mapping from ids to labels are done in the config:
https://pp.opendevelopmentcambodia.net/wp-admin/post.php?post=96282&action=edit

![screenshot from 2016-12-05 18-48-52](https://cloud.githubusercontent.com/assets/384894/20895869/8993eaca-bb1b-11e6-82a2-5dfc878ccc1e.png)

Please change those values accordingly.

Closing.
