### ISSUE TITLE
Remove the data visualization on ODC's law's pages

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#52]
Suggests to remove the data vitalization of record and taxonomy on the law page. 
There is not much document available on the site, so data vitalization presentation will not be necessary.

**Comment by acorbi** [comment]
@Huyeng agreed. We are currently preparing a new itearation of the laws page to be discussed, reviewd and approved by ODM and partners before being deployed on PROD.

Removing the data viz from laws pages now.
