### ISSUE TITLE
The title of table and types of document types are not translated on Khmer site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#54]
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/21339325/f47f34ac-c6b0-11e6-807c-ea4f4b14fc17.jpg)

**Comment by Huyeng** [comment]
@acorbi, those strings are translated, i thought. Please let me know if those have not translated.

**Comment by acorbi** [comment]
@Huyeng I have updated the translations for wp-odm_tabular. those strings were translated on wpckan. Deploying to PP and PROD now
