### ISSUE TITLE
Change the color how group record to country color

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_tabular_pages#75]
For example on ODC site, the color of screenshot below should be green instead the dark blue to make it be consistent as profile page: https://opendevelopmentcambodia.net/km/profiles/natural-protected-areas/
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/21451993/496bfb8a-c936-11e6-8e34-98fbb4d745fd.jpg)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/wp-odm_theme/commit/6c69ec773e17f85010d5ffd22561504826af49fa
