### ISSUE TITLE
Inconsistent search results for WP and CKAN

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_tabular_pages#88]
Test example - ENVIRONMENT
In WP: 13 records
![image](https://cloud.githubusercontent.com/assets/14996905/21557931/0d12fde0-ce87-11e6-8e7b-2914134537c0.png)
In CKAN: 189 records
![image](https://cloud.githubusercontent.com/assets/14996905/21557936/229a1932-ce87-11e6-8205-ba80d52ec11b.png)

The search in CKAN is searching all of the metadata that mentions the term 'environment' and records in WP are only those that have the term in the title. Please make consistent to search all the metadata fields so that the same number of results is found.

**Comment by acorbi** [comment]
That screen does not show the unified filter box. That implementation might be outdated.

@prustar quoting from my comment on https://docs.google.com/document/d/1bsDasgy-t2mdDZ1NNaV17FDluxEoxlAtej2M60khcsc/edit#:

+pchung@ewmi-odi.org I am not sure why you are getting those results..

I do:

1. go to https://pp.opendevelopmentcambodia.net/tabular/laws-profiles-and-agreements/?clear
2. enter "Environment" on the textual search field
3. Click "Search" Button
4. I obtain 189 results, exactly as it happens in CKAN (See screenshot)

![screenshot from 2016-12-30 11-38-55](https://cloud.githubusercontent.com/assets/384894/21563665/93d11630-ce84-11e6-89ed-d8bcb265ed1b.png)

The same happens with the search term "Law". I obtain the results I am expecting the same as in CKAN (519 results)

Can you please indicate concrete steps to reproduce the issue you are raising? Which browser are you using?

**Comment by prustar** [comment]
@acorbi -- seems to be fixed, can't reproduce it now.
