### ISSUE TITLE
Javascript error when number of columns is not 4

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#89]
Currently, the laws pages on ODC are configured to present the information in 4 columns. See https://pp.opendevelopmentcambodia.net/tabular/laws-profiles-and-agreements/

![screenshot from 2016-12-30 10-59-49](https://cloud.githubusercontent.com/assets/384894/21563159/365bd85a-ce7f-11e6-94cb-e5343bc0d572.png)

If one column is removed, a javascript error gets thrown:

![screenshot from 2016-12-30 11-02-40](https://cloud.githubusercontent.com/assets/384894/21563187/821843dc-ce7f-11e6-9265-f0183bbd2b41.png)

The problem probably relies on the fact that there is some code which takes for granted that there are ALWAYS 4 columns configured.  Probably, following line is relevant:

https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/blob/master/post-types/templates/single-tabular.php#L361

This needs to be coded in a generic/flexible way.

@Huyeng you were working recently with the column width. can you please take over this task?

**Comment by Huyeng** [comment]
I will help to fix this.

**Comment by Huyeng** [comment]
I don't have any problem with removing the column, see the screenshot below:
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/21636763/72041c6c-d296-11e6-8bff-6681dfe4a5ef.jpg)

**Comment by acorbi** [comment]
@Huyeng I already opened a PR some days ago with the fix for this issue. Please review https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/pull/90 and merge if you agree.
