### ISSUE TITLE
General Comment

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_tabular_pages#9]
![image](https://cloud.githubusercontent.com/assets/14996905/16871193/caff11d0-4a85-11e6-8374-c8c098f6e034.png)

White space: perhaps a visual at the top? Not priority and already included in the 2.1 design but there is that gap at the top that could be filled with something? Example: bar chart of laws by taxonomy, timeline of adopted laws, law types donut etc. 

I also clicked on a random dataset and there was an error in the record. But there's no admin function to take us to the record in CKAN to fix. Could this be integrated as standard for all pages that display CKAN records. 

On Dataset page paragraph spacing is a little large particularly in this example of a long title: 

![image](https://cloud.githubusercontent.com/assets/14996905/16871324/974042be-4a86-11e6-9e45-0528cfdbf12b.png)

**Comment by acorbi** [comment]
> White space: perhaps a visual at the top? Not priority and already included in the 2.1 design but there is that gap at the top that could be filled with something? Example: bar chart of laws by taxonomy, timeline of adopted laws, law types donut etc.

The gap is not present anymore.

> I also clicked on a random dataset and there was an error in the record. But there's no admin function to take us to the record in CKAN to fix. Could this be integrated as standard for all pages that display CKAN records.

This issue has been already raised on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/172

> On Dataset page paragraph spacing is a little large particularly in this example of a long title: 

This issue has been already raised on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/604

Closing
